site_name: Dynamic On Demand Analysis Service 
theme:
  name: material
  icon:
    logo: material/cloud
  palette:
    primary: 'Blue'
    accent: 'Red'

repo_name: 'DODAS-TS/dodas-doc'
repo_url: 'https://github.com/DODAS-TS/dodas-doc'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/DODAS-TS'

markdown_extensions: 
  - codehilite

nav:
- Home: 'README.md'
- Introduction: introduction.md
- Overview: 
  - The general idea: overview/general-idea.md
  - Architecture: overview/architecture.md
  - Schematic workflow: overview/workflow.md
- The Enabling Facility: the-enabling-facility.md
- Supported solutions:
  - HTCondor cluster for CMS: supported-solutions/cms.md
  - HTCondor cluster for AMS: supported-solutions/ams.md
  - HTCondor generic use case: supported-solutions/htc.md
  - XCache on demad: supported-solutions/xcache.md
  - Spark analytics : supported-solutions/spark.md
- Getting Started:
  - Before starting:
    - DODAS client installation:  getting-started/before-starting/dodas-client-installation.md
    - DODAS client configuration: 
      - Openstack providers: getting-started/before-starting/providers/os.md
      - GCP: getting-started/before-starting/providers/gcp.md
      - Azure: getting-started/before-starting/providers/azure.md
      - AWS: getting-started/before-starting/providers/aws.md
      - Bare Metal: getting-started/before-starting/providers/bare.md
  - Quick start: getting-started/quick-start.md
  - Tutorials:
    - HTCondor cluster for CMS: getting-started/tutorials/cms-recipe.md
    - HTCondor cluster for AMS: getting-started/tutorials/ams-recipe.md
    - HTCondor generic use case: getting-started/tutorials/htc-recipe.md
    - XCache on demad: getting-started/tutorials/xcache-recipe.md
    - Spark analytics : getting-started/tutorials/spark-recipe.md
- FAQ: faq.md
- Troubleshooting: troubleshooting.md
- Roadmap: known-issues.md 
- Contact us: contacts.md


